project:
  type: default
  execute-dir: project
  
author: 
  - name: Maël Delem
    orcid: 0009-0005-8518-1991
    email: mael.delem@univ-lyon2.fr
    corresponding: true
    url: https://emc.univ-lyon2.fr/equipes/memoire-emotion-et-attention-mea/delem-mael
    affiliations:
    - id: emc
      name: Study of Cognitive Mechanisms (EMC) Laboratory, Université Lumière Lyon 2
      city: Lyon
      country: France
      url: https://emc.univ-lyon2.fr

date-modified: last-modified

bibliography:
  - "bibliography/references.bib" 
csl: "bibliography/apa.csl"

execute:
  freeze: false
  warning: false
  error: false
  message: false

crossref:
  chapters: true

format:

  html:
    embed-resources: true 
    format-links: false     # no links to other formats
    theme: 
      light:
        - scss/custom-theme.scss
        - scss/default-vars.scss
        - scss/colours-light.scss
      dark:
        - scss/custom-theme.scss
        - scss/default-vars.scss
        - scss/colours-dark.scss
    highlight-style: github
    lightbox: true          
    code-fold: true         
    code-tools: true        
    code-annotations: hover 
    title-block-banner: true
    toc: true
    toc-location: right
    toc-depth: 2
    toc-expand: 1
    number-sections: true
    number-depth: 2
    filters:
      - add-code-files

  # Word
  docx: 
    reference-doc: "docs/custom-reference-doc.docx"
    echo: false
    # extension to add a block with authors in .docx format
    filters:
      - authors-block


