```{r}
#| label: setup
#| echo: true
#| code-fold: false

if (!requireNamespace("pacman")) install.packages("pacman")
pacman::p_load(
  conflicted, 
  fs, 
  here,
  ggplot2,
  patchwork,
  purrr,
  sessioninfo
)

# source all our functions
dir_ls(here("R"), type = "file", recurse = TRUE) |> walk(source)

# resolve package conflicts
conflicts_prefer(
  dplyr::filter(), 
  dplyr::select(),
  scales::rescale(), 
  purrr::map(),
  base::as.data.frame(),
  base::which.max(),
  .quiet = TRUE
  )
```

```{r}
#| label: load-data

df <- import_jatos_data()$data_final

partial_correlation_vars <- c(
  "visual_imagery", "sensory_imagery", "spatial_imagery", "verbal_strategies",
  "fluid_intelligence", "verbal_reasoning", "span_spatial")

dfs_to_cluster <- list(
  # Solution 1: simply scale then cluster the embedded raw variables
  scaled = 
    df |> 
    scale_vars() |> 
    select(vviq:span_digit, score_similarities)
  # Solution 2: manual reduction based on partial correlation first
  # reduced = 
  #   df |> 
  #   reduce_vars() |> 
  #   select(any_of(partial_correlation_vars)) |> 
  #   mutate(across(everything(), ~as.numeric(scale(.))))
)
```

# Computing clustering consensus

```{r}
#| label: embed-and-cluster

cluster_results <- 
  map(
    dfs_to_cluster, 
    embed_and_cluster, 
    df = df
  )
```

```{r}
#| label: print-summary

walk(cluster_results, ~walk(.$summary, print))
```

# Number of clusters

```{r}
#| fig-width: 10
#| fig-height: 6

p1 <-
  cluster_results$scaled$clustering[[3]]$E |> 
  diceR::graph_cdf() + 
  theme_minimal() + 
  facet_grid(~Method) + 
  scale_colour_brewer() + 
  theme(panel.border = element_rect(colour = "grey50", fill = NA))

p2 <-
  cluster_results$scaled$clustering[[3]]$E |> 
  diceR::graph_delta_area() + 
  theme_minimal() + 
  facet_grid(~Method) + 
  scale_colour_brewer() + 
  theme(panel.border = element_rect(colour = "grey50", fill = NA))

p1 / p2
```


# Variable embeddings

```{r}
#| label: plot-embeddings
#| fig-width: 8
#| fig-height: 4

p_embeds <- plot_clusters_embeds(cluster_results, df)

print(p_embeds)

ggsave(
  filename = "figures/cluster-embeddings.pdf",
  plot = p_embeds,
  width = 180,
  height = 90,
  units = "mm"
)
```

# Cluster radars

```{r}
cluster_results <- 
  tibble(
    name        = c("scaled", "reduced"),
    df_to_clust = list(
      # Solution 1: simply scale then cluster the embedded raw variables
      df |> 
        scale_vars() |> 
        select(vviq:span_digit, score_similarities),
      # Solution 2: manual reduction based on partial correlation first
      df |>
        reduce_vars() |>
        select(any_of(partial_correlation_vars)) |>
        mutate(across(everything(), ~as.numeric(scale(.))))
    )
  ) |> 
  rowwise() |> 
  mutate(results = list(embed_and_cluster(df_to_clust, df))) |> 
  unnest(results)
```

```{r}
cluster_results |>
# cluster_results_ap |> 
  select(
    name, 
    method, 
    contains("q_"),
    renamed_clusters
  ) |> 
  unnest(!c(name, method)) |> 
  mutate(method = case_match(method, "DiffusionMaps" ~ "DM",.default = method)) |> 
  rowwise() |>
  mutate(q = sum(c_across(contains("q_"))), .keep = "unused") |>
  mutate(
    A_weight = sum(c_across(contains("cluster")) == 1) * q |> round(2),
    B_weight = sum(c_across(contains("cluster")) == 2) * q |> round(2),
    C_weight = sum(c_across(contains("cluster")) == 3) * q |> round(2)
  ) |> 
  ungroup() |> 
  select(!c(contains("cluster"), q)) |> 
  pivot_wider(
    names_from = c(name, method), 
    values_from = c(contains("weight"))
  ) |> 
  rowwise() |>
  mutate(
    A_score = sum(c_across(contains("A_weight"))),
    B_score = sum(c_across(contains("B_weight"))),
    C_score = sum(c_across(contains("C_weight"))),
    cluster = case_when(
      A_score > B_score & A_score > C_score ~ "A",
      B_score > A_score & B_score > C_score ~ "B",
      C_score > A_score & C_score > B_score ~ "C",
      TRUE ~ "WAT why"
    ),
    .keep = "unused"
  ) |> 
  ungroup() |> 
  mutate(
    id = df$id,
    group = df$group,
    g_vviq  = df$vviq,
    g_spatial = df$osivq_s,
    g_verbal  = df$osivq_v,
    g_raven = df$score_raven,
    g_sri   = df$score_sri
  )
```


```{r}
#| label: plot-radars
#| fig-width: 8
#| fig-height: 4

df_clustered <- 
  df |> 
  # add_clusters(cluster_results$scaled,  "scaled") |>
  # add_clusters(cluster_results$reduced, "reduced") |>
  mutate(across(contains("cluster"), ~ rename_clusters(., vviq))) |> 
  align_clusters() |>
  scale_vars() |> 
  get_long_format() |> 
  mutate(
    Variable = 
      Variable |> 
      str_replace("Reading\ncomprehension", "Reading") |> 
      str_replace("Psi-Q Sensations", "Psi-Q Sens.") |> 
      str_replace("Psi-Q Feelings", "Psi-Q Feel.") |>  
      str_replace("Audition", "Auditory") |> 
      factor() |> 
      fct_inorder() |> 
      fct_relevel("VVIQ", after = Inf)
  )

p1 <-
  plot_clusters_radar(
    df_clustered,
    value ~ Variable + Cluster,
    palette = c("#56B4E9", "#E69F00", "#009E73")
  ) +
  theme(plot.margin = margin(0, 3.5, 0, 2, "mm"))

p2 <-
  plot_clusters_radar(
    df_clustered,
    value ~ Variable + Subcluster,
    palette = c("#56B4E9", "#E69F00", "#F5C710", "#009E73")
  ) +
   theme(plot.margin = margin(0, 2, 0, 3.5, "mm"))

p_radars <- p1 + p2

print(p_radars)

ggsave(
  filename = "figures/cluster-radars.pdf",
  plot = p_radars,
  width = 180,
  height = 90,
  units = "mm"
)
```


