```{r}
if (!requireNamespace("pacman")) install.packages("pacman")
pacman::p_load(
  BiocManager,
  conflicted, 
  here,
  factoextra,
  fs, 
  ggplot2,
  mclust,
  NbClust,
  patchwork,
  purrr,
  sessioninfo
)

source(here("R/01_import/import-jatos-data.R"))
dir_ls(here("R/02_wrangle"), type = "file", recurse = TRUE) |> walk(source)
source(here("R/03_model/correlate-vars.R"))
source(here("R/03_model/model-groups.R"))
source(here("R/04_plot/plot-clusters-radar.R"))

# resolve package conflicts
conflicts_prefer(
  dplyr::filter(), 
  dplyr::select(),
  scales::rescale(), 
  purrr::map(),
  .quiet = TRUE
  )
```

```{r}
df <- import_jatos_data()$data_final
```

```{r}
corrs_simple  <- correlate_vars(df, partial = FALSE, correction = "bonferroni")
corrs_partial <- correlate_vars(df, partial = TRUE,  correction = "bonferroni")
```

```{r}
#| warning: false

selected_vars <- c(
  "visual_imagery", "sensory_imagery", "spatial_imagery", "verbal_strategies",
  "fluid_intelligence", "verbal_reasoning", "span_spatial"
)

bic <- df |> scale_reduce_vars() |> select(any_of(selected_vars)) |> mclustBIC()

clustering <- 
  df |> 
  scale_reduce_vars() |> 
  select(any_of(selected_vars)) |>
  Mclust(verbose = FALSE)

df2 <- 
  merge_clusters(df_raw = df, df_reduced = scale_reduce_vars(df), clustering) |> 
  scale_vars() |> 
  get_longer()
```

```{r}
models_path <- here("data/r-data-structures/models.rds")

if (!file_exists(models_path)) {
  group_models      <- df2 |> model_groups(groups = Group)
  cluster_models    <- df2 |> model_groups(groups = Cluster)
  subcluster_models <- df2 |> model_groups(groups = Subcluster)
  
  saveRDS(
    list(
      group_models      = group_models,
      cluster_models    = cluster_models,
      subcluster_models = subcluster_models
      ), 
    models_path)
  
} else models <- readRDS(models_path)
```

# Checks

```{r}
df2 |> 
  select(id, Subcluster) |> 
  distinct() |> 
  group_by(Subcluster) |> 
  count()
```

# Plots

## Correlations

```{r}
#| fig-width: 8
#| fig-height: 5

plot_correlations(corrs_partial)

ggsave(
  here("figures/correlations-partial.pdf"),
  width = 180,
  height = 120,
  units = "mm",
  dpi = 600
)

plot_correlations(corrs_simple)

ggsave(
  here("figures/correlations-simple.pdf"),
  width = 180,
  height = 120,
  units = "mm",
  dpi = 600
)

```

## Number of components

```{r}
#| fig-cap: "Comparison of the goodness of fit of mixture models as a function of model type and number of components. A high BIC indicates a good model fit. The three-letter acronyms describe the components of the mixture model. The first letter describes the volume of the components, the second the shape and the last the orientation. E = equal variance, V = variable variance. Acronyms of the form ‘XII’ indicate spherical components, ‘XXI’ diagonal components and ‘XXX’ ellipsoidal components."
#| fig-width: 3.5
#| fig-height: 3.5

plot_clusters_bic(clustering)

ggsave(
  here("figures/clusters-bic.pdf"),
  width = 88,
  height = 88,
  units = "mm",
  dpi = 600
)
```


## Radars

```{r}
df2 |> 
  mutate(
    Variable = 
      Variable |> 
      str_replace("Reading\ncomprehension", "Reading") |> 
      str_replace("Psi-Q Sensations", "Psi-Q Sens.") |> 
      str_replace("Psi-Q Feelings", "Psi-Q Feel.") |>  
      str_replace("Audition", "Auditory") |> 
      factor() |> 
      fct_inorder() |> 
      fct_relevel("VVIQ", after = Inf)
  ) |> 
  plot_clusters_radar(
    value ~ Variable + Cluster,
    palette = c("#56B4E9", "#E69F00", "#009E73")
  )
```

